# Generated by Django 3.2.10 on 2022-02-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(max_length=120, unique=True, verbose_name='Código Externo')),
                ('internal_reference', models.CharField(max_length=120, unique=True, verbose_name='Código Interno')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('enrollment', 'Matriculado'), ('cancelated', 'Cancelado')], max_length=20, verbose_name='Estado de Matrícula')),
                ('payment_information', models.TextField(verbose_name='Información de pago')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', related_query_name='enrollment', to='courses.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', related_query_name='enrollment', to='students.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
