exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
# fail_fast: true

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus", "--keep-runtime-typing"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: file-contents-sorter
      - id: fix-encoding-pragma
        args: ['--remove']

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--remove-unused-variable',
          '--remove-duplicate-keys',
          '--ignore-init-module-imports'
          ]

  - repo: https://github.com/odwyersoftware/brunette
    rev: 0.2.2
    hooks:
      - id: brunette
        args:
        - --config=backend/setup.cfg
        - --single-quotes
        language_version: python3

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config=backend/setup.cfg']
        additional_dependencies:
          - flake8-isort
          - flake8-black
        language_version: python3

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        args:
        - --rcfile=backend/.pylintrc
        - --errors-only
        - --disable=no-name-in-module,import-error
        - --ignore=migrations

  -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.2.2
      hooks:
        - id: python-safety-dependencies-check

  -   repo: https://github.com/PyCQA/bandit
      rev: 1.7.1
      hooks:
        - id: bandit
          args:
          - --exclude=tests
