version: "3.8"

services:
  web: &web
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    restart: unless-stopped
    command: uvicorn server.asgi:application --host 0.0.0.0 --reload
    volumes:
      - ./backend:/home/server:z
    ports:
      - "8000:8000"
    env_file:
      - .envs/development/web.env
    networks:
      - project-network

networks:
  project-network:
    name: test-network
