# Generated by Django 3.2.10 on 2022-02-02 12:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-100', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, verbose_name='URL segura de categoria')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='courses.category', verbose_name='parent of category')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('internal_reference', models.CharField(max_length=120, unique=True, verbose_name='Código Interno')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(help_text='format: true=product visible', verbose_name='Curso Disponible')),
                ('category', mptt.fields.TreeManyToManyField(to='courses.Category')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('internal_reference', models.CharField(max_length=120, unique=True, verbose_name='Código Interno')),
                ('available_vacancie', models.IntegerField(default=0, verbose_name='Vacantes disponibles')),
                ('max_vacancies', models.IntegerField(default=0, verbose_name='Vacantes Máximas')),
                ('student_enrollment', models.IntegerField(default=0, verbose_name='Alumnos Matriculados')),
                ('start_hour', models.CharField(max_length=15, verbose_name='Hora de Inicio')),
                ('end_hour', models.CharField(max_length=15, verbose_name='Hora de Fin')),
                ('qty_session', models.IntegerField(default=0, verbose_name='Cantidad de Sesiones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classroom Disponible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', related_query_name='classroom', to='courses.course')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
