# Generated by Django 3.2.10 on 2022-02-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('internal_reference', models.CharField(max_length=255, verbose_name='Código Interno')),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('image', models.ImageField(upload_to='students/', verbose_name='Imagen')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('college', models.CharField(max_length=180, verbose_name='Colegio')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('qty_brother', models.IntegerField(default=0, verbose_name='Número de Hermanos')),
                ('age', models.IntegerField(default=1, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electronico')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono Movil')),
                ('occupation', models.CharField(max_length=80, verbose_name='Ocupación')),
                ('document_type', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'DNI'), ('PPT', 'PPT')], default='DNI', max_length=5, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student', related_query_name='parent_student', to='students.student')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
    ]
